<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>de.justvotes</groupId>
        <artifactId>justvotes</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>
    <artifactId>adapters</artifactId>
    <dependencies>
        <dependency>
            <groupId>de.justvotes</groupId>
            <artifactId>api-contract</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>de.justvotes</groupId>
            <artifactId>poll-management</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>de.justvotes</groupId>
            <artifactId>template-catalog</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-tx</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.persistence</groupId>
            <artifactId>jakarta.persistence-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
